live_config_reload = true

[font]
size = 8.0

[font.normal]
family = "SFMono Nerd Font"
style = "Regular"

[window]
opacity = 0.95

[window.padding]
x = 1
y = 1

[selection]
save_to_clipboard = true

# Colors (Blood Moon)
[colors]

# Default colors
[colors.primary]
background = '0x10100E'
foreground = '0xC6C6C4'

# Normal colors
[colors.normal]
black =   '0x10100E'
red =     '0xC40233'
green =   '0x009F6B'
yellow =  '0xFFD700'
blue =    '0x0087BD'
magenta = '0x9A4EAE'
cyan =    '0x20B2AA'
white =   '0xC6C6C4'

# Bright colors
[colors.bright]
black =   '0x696969'
red =     '0xFF2400'
green =   '0x03C03C'
yellow =  '0xFDFF00'
blue =    '0x007FFF'
magenta = '0xFF1493'
cyan =    '0x00CCCC'
white =   '0xFFFAFA'
