format = """
$username\
$hostname\
$directory\
$git_branch \
$jobs
"""

# Inserts a blank line between shell prompts
add_newline = true

[directory]
truncation_length = 10
truncate_to_repo = false

[git_branch]
disabled = false

[jobs]
disabled = false
symbol = '⚡'
number_threshold = 1
symbol_threshold = 1
style = "bold fg:yellow"
