# Get editor completions based on the config schema
# "$schema" = 'https://starship.rs/config-schema.json'


format = """
$username\
$hostname\
$directory\
$git_branch
"""

# Inserts a blank line between shell prompts
add_newline = true

[directory]
truncation_length = 3
truncate_to_repo = false

[git_branch]
disabled = false
